# Hulios project funding configuration

custom:
  - "https://mempool.space/address/bc1q0gllvd7fe2y48emjd4shf42ul3cl4pgda5zpqz"
  - "https://tronscan.org/#/address/TQWUmTATa8sDntobTNGkLmbgmHVS9iWCRx"
  - "https://etherscan.io/address/0x16aFd1De7889071194A026D79393eb3CE659181e"
