[target.bpfel-unknown-none]
runner = "true"
linker = "bpf-linker"

[build]
target = "x86_64-unknown-linux-gnu"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[target.x86_64-unknown-linux-gnu.env]
OPENSSL_NO_VENDOR = "1"
