[package]
name = "hulios-cli"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
clap = { workspace = true, features = ["derive", "env"] }
serde = { workspace = true, features = ["derive"] }
toml = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
